export enum SpiritCategoryEnum {
  Irish = 'irish',
  Scotch = 'scotch',
  Bourbon = 'bourbon',
  WHISKY = 'whisky',
  VODKA = 'vodka',
  GIN = 'gin',
  RUM = 'rum',
  TEQUILA = 'tequila',
  COGNAC = 'cognac',
  ARMAGNAC = 'armagnac',
  CALVADOS = 'calvados',
  BRANDY = 'brandy',
  LIQUEUR = 'liqueur',
  SOJU = 'soju',
  MAKGEOLLI = 'makgeolli',
  TRADITIONAL = 'traditional',
  OTHER = 'other',
}

export enum CaskEnum {
  BOURBON = 'bourbon',
  SHERRY = 'sherry',
  WINE = 'wine',
  PORT = 'port',
  MADEIRA = 'madeira',
  RUM = 'rum',
  BEER = 'beer',
  VIRGIN = 'virgin',
  OTHER = 'other',
}
